In [59]:
#1. Create an if statement: if 'age' is greater than or equal to 25, print "Renting a car is more affordable", 
# however if 'age' is less than 25, print "Renting a car is very expensive."
age = 16
if age >= 25:
    print("Renting a car is more affordable")
elif age < 25:
    print("Renting a car is very expensive.")
else:    
    print('error')

Renting a car is very expensive.


In [58]:
#2. Create and chain an if-else  statement: 
# if 'age' is greater than or equal to 25, print "Renting a car is more affordable." 
# If 'age' is less than 25 but greater than or equal to 18, print "Renting a car is very expensive." 
# Finally, if age is less than 18, print "You cannot legally rent a car."
if age >= 25: 
    print("Renting a car is more affordable." )
elif age < 25 and age >= 18:
    print("Renting a car is very expensive." )
elif age < 18:
    print("You cannot legally rent a car.")
else:
    print('error')

You cannot legally rent a car.


In [57]:
#3. Loop over the following string to 
# (1) count all the characters in the string and print out all the vowels -- 
# "The quick brown fox jumps over the lazy dog"
str1 = "The quick brown fox jumps over the lazy dog" 
v = 'aeiouAEIOU'

print('# of Characters: ', len(str1))
print('Vowel List:')
for vowels in str1:
    if vowels in v:
        print (vowels)

# of Characters:  43
Vowel List:
e
u
i
o
o
u
o
e
e
a
o


In [56]:
#4. Write a nested loop that prints out every piece of clothing from the `couture` list, 
# in every fashionable color from the `panettone` set: 
# couture = ["trousers", "blouse", "bandana", "cumber band",
# "blazer", "vest", "french beret", "scarf", "stole"] and 
# panettone = {"cerise", "fuchsia", "aqua", "maple", "auburn", "burnt sienna", 
# "gunmetal blue", "Dark Sapphire"}
couture = ["trousers", "blouse", "bandana", "cumber band","blazer", "vest", "french beret", "scarf", "stole"]
panettone = {"cerise", "fuchsia", "aqua", "maple", "auburn", "burnt sienna", "gunmetal blue", "Dark Sapphire"}

for x in couture:
    for y in panettone:
        print(x,y)

trousers fuchsia
trousers burnt sienna
trousers cerise
trousers auburn
trousers maple
trousers aqua
trousers Dark Sapphire
trousers gunmetal blue
blouse fuchsia
blouse burnt sienna
blouse cerise
blouse auburn
blouse maple
blouse aqua
blouse Dark Sapphire
blouse gunmetal blue
bandana fuchsia
bandana burnt sienna
bandana cerise
bandana auburn
bandana maple
bandana aqua
bandana Dark Sapphire
bandana gunmetal blue
cumber band fuchsia
cumber band burnt sienna
cumber band cerise
cumber band auburn
cumber band maple
cumber band aqua
cumber band Dark Sapphire
cumber band gunmetal blue
blazer fuchsia
blazer burnt sienna
blazer cerise
blazer auburn
blazer maple
blazer aqua
blazer Dark Sapphire
blazer gunmetal blue
vest fuchsia
vest burnt sienna
vest cerise
vest auburn
vest maple
vest aqua
vest Dark Sapphire
vest gunmetal blue
french beret fuchsia
french beret burnt sienna
french beret cerise
french beret auburn
french beret maple
french beret aqua
french beret Dark Sapphire
french beret gunmetal

In [31]:
#5. Use range as a loop to calculate the sum of all the numbers from 1 to 100
total = 0
for x in range(1,101):
    total += x
print(total)

5050


In [45]:
#6. Print the second item in this fruits list.["apple", "banana", "cherry"]
fruit =  ["apple", "banana", "cherry"]  
print(fruit[1]) 

#7. Change the value from "apple" to "kiwi", in the fruits list. ["apple", "banana", "cherry"]
fruit[0] = 'kiwi'
print(fruit)

#8. Use the append method to add "orange" to the fruits list. ["apple", "banana", "cherry"]
fruit.append('orange')
print(fruit)

#9. Use the insert method to add "lemon" as the second item in the fruits list.["apple", "banana", "cherry"]
fruit.insert(1,'lemon')
print(fruit)

#10. Use the remove method to remove "banana" from the fruits list.["apple", "banana", "cherry"]
fruit.remove('banana')
print(fruit)

#11. Use negative indexing to print the 3rd and 2nd to last items in the list.
#["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
f2 = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(f2[-3:-1])
#12. Use a range of indexes to print the third, fourth, and fifth item in the list.
#["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(f2[2:5])

#13. Use the correct syntax to print the number of items in the list.
#["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print('# of items:', len(f2))

#14. Use the correct syntax to sort this list in reverse order
#["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
f2.sort(reverse = True)
print(f2)


banana
['kiwi', 'banana', 'cherry']
['kiwi', 'banana', 'cherry', 'orange']
['kiwi', 'lemon', 'banana', 'cherry', 'orange']
['kiwi', 'lemon', 'cherry', 'orange']
['kiwi', 'melon']
['cherry', 'orange', 'kiwi']
# of items: 7
['orange', 'melon', 'mango', 'kiwi', 'cherry', 'banana', 'apple']


In [49]:
#15. Use the DateTime module to get Current Date and Time, and save it to a variable. 
# Then extract just the month name form that variable.
import datetime as dt

myTime = dt.datetime.now()

print(myTime)
print('Month:', myTime.strftime('%B'))


2022-11-21 16:07:16.812628
Month: November


In [52]:
#16. Write a simple function that takes 2 parameters -- a  first name and a day name.
#Set a default value for the day name of Sunday.
# Have the function print out a greeting 
# -- using the parameters -- that says something like 
# "Hi first-name! Happy day-name!". 
# Remember to use the variables in the greeting to replace first-name and day-name.  
# Invoke this function with 2 variables.
# Invoke this function with 1 variable only.

def firstnameday (name, day = "Sunday"):
    print("Hi,"+name+"! Happy "+day+"!")

firstnameday('Osvaldo', 'Friday')
firstnameday('Charlie')



Hi,Osvaldo! Happy Friday!
Hi,Charlie! Happy Sunday!


In [55]:
#17. Import NumPy and create an array with a shape of ... (2, 3, 2)
import numpy as np

array = np.arange(12).reshape(2,3,2)
print(array)

#18. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20
linar = np.linspace(0, 20, num=6)
print(linar)

#19. Make a Deep Copy of the above array you created.
import copy 
linar2 = copy.deepcopy(linar)
print(linar2)   


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


# 20. What are 2 reasons we use NumPy over Python Lists
- NumPy arrays are faster and use less space than python lists.